### ISSUE TITLE
Drop the support for Python 2.6

### ISSUE THREAD

**Issue by tvieira** [fedora-infra/fedmsg#376]
I think we should drop the support for python 2.6. Many dependencies (i.e. Twisted, which is a dependency for moksha.hub) already dropped the support for 2.6. To go forward we would have to lock versions which increases the complexity of maintenance.

**Comment by ncoghlan** [comment]
I just ran into this, with a docs PR failing due to Python 2.6 still being in the test matrix, but Twisted not being capped to 15.4 on Python 2.6.

Theoretically, the restriction could be limited to just Python 2.6 by added "twisted < 15.5; python_version < '2.7'" to the requirements, but then you run into the problem of needing a sufficiently recent pip that understands requirements markers.

If there's still a use case where fedmsg needs to run in the system Python on RHEL 6, then the simplest option might be to add the "twisted < 15.5" restriction universally until Fedora Infrastructure only needs to worry about RHEL 7 and Fedora.

**Comment by ashcrow** [comment]
If it does need to run on RHEL 6 there is always [Software Collections](https://www.softwarecollections.org/en/scls/rhscl/python27/)
