### ISSUE TITLE
crl handling improvements

### ISSUE THREAD

**Issue by nirik** [fedora-infra/fedmsg#481]
Right now when the crl expires, fedmsg just stops. It might be nice to retry on a backoff to fetch a new crl.pem, ie try and fetch/check a new one after a minute, 10 minutes, etc. 

Also, fedmsg tries to store the crl in the users homedir if it's not able to write to /var/run/fedmsg. This results in bad things like if fedmsg is running as apache storing a crl.pem in /usr/share/httpd/.local/var/run/fedmsg/crl.pem. In this case might be better to store in /tmp/ somewhere?

**Comment by jeremycline** [comment]
> Right now when the crl expires, fedmsg just stops. It might be nice to retry on a backoff to fetch a new crl.pem, ie try and fetch/check a new one after a minute, 10 minutes, etc.

I'm torn about whether this would be better than the "fast fail" approach. If the CRL is expired/invalid, it's going to be a reasonably long time before it's fixed. How long do we wait? While each thread is waiting for a valid CRL, messages will stack up in the ZMQ queue and get dropped eventually (or, if there's no high water mark the process will get OOM killed).

It would strike me as odd if a program sat around and retried for a long time if a x509 certificate had expired/was invalid, so doing that for a CRL seems odd.

> fedmsg tries to store the crl in the users homedir if it's not able to write to /var/run/fedmsg. This results in bad things like if fedmsg is running as apache storing a crl.pem in /usr/share/httpd/.local/var/run/fedmsg/crl.pem. In this case might be better to store in /tmp/ somewhere?

Whatever we do, we should also fix #365 as part of this. There are a few options I've been thinking about with the whole CRL situation:

* Require the CRL to be a file path rather than a URL and handle updating it via configuration management.

* _Always_ write the CRL to a thread-local temporary directory. This means each time you start fedmsg-hub it'll need to go get the CRL for each thread.

* Use dogpile.cache and never write the network-retrieved CRL to the disk.

* Something else I haven't thought of yet

Do any of those options sound appealing? Do any sound unappealing?

**Comment by nirik** [comment]
I suppose fast fail would be ok, but it should pull a new crl on restart then, because otherwise you have to find out where it stored the old expired one and remove it, and then restart. ;( 

I'm fine with making the crl a config option, or always getting it on start for each thread. Either of those seems reasonable to me, with a few tradeoffs for each.

**Comment by nirik** [comment]
Additionally, it seems like if a crl.pem is currently downloaded and it's expired, it keeps using that forever. It might be nice to always check for a new one on startup and if there is a newer one, download it and replace the old expired cached one.

**Comment by jeremycline** [comment]
I tend to lean towards having it be a file path and not dealing with the whole download/retry/cache expiry business. It's simple and easy. I assume we already have to use Ansible to deploy the new CRL anyway, so pushing it directly to consumers seems just as easy.
